/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-03-13 16:19:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Perfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/daniel/Documents/UnEx/PI/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meneamedc/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1455219336000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write(" \t<title>nombreusuario</title>\n");
      out.write(" \t<link rel=\"shortcut icon\" href=\"https://mnmstatic.net/v_40/img/favicons/logo_196x196.png\" type=\"image/png\" sizes=\"196x196\">\n");
      out.write(" \t<link rel=\"shortcut icon\" href=\"https://mnmstatic.net/v_40/img/favicons/logo_64x64.png\" type=\"image/png\" sizes=\"64x64\">\n");
      out.write(" \t<link rel=\"shortcut icon\" href=\"https://mnmstatic.net/v_40/img/favicons/logo_16x16.png\" type=\"image/png\" sizes=\"16x16\">\n");
      out.write(" \t<link rel=\"shortcut icon\" href=\"https://mnmstatic.net/v_40/img/favicons/logo_128x128.png\" type=\"image/png\" sizes=\"128x128\">\n");
      out.write(" \t<link rel=\"stylesheet\" href=\"css/base.css\">\n");
      out.write(" \t<link rel=\"stylesheet\" href=\"css/ver-perfil.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"head\" id=\"nombre-categorias\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<img alt=\"\" src=\"img/menu.png\">\n");
      out.write("\t\t\t<a href=\"lista-noticias.html\"><img alt=\"\" src=\"img/logo-top.png\"></a>\n");
      out.write("\t\t\t<img alt=\"\" src=\"img/door.png\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"categorias\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a>cultura y tecnologia</a></li>\n");
      out.write("\t\t\t\t<li><a>edicion general</a></li>\n");
      out.write("\t\t\t\t<li><a>deportes</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"rigth login-succ\">\n");
      out.write("\t\t\t<a href=\"ver-perfil.html\">nombreusuario</a>\n");
      out.write("\t\t\t<img id=\"avatar-login\" alt=\"avatar usuario\" src=\"img/pic-test.jpeg\">\n");
      out.write("\t\t\t<img id=\"shutdown\" alt=\"\" src=\"img/logout.png\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"head\" id=\"logo-search\">\n");
      out.write("\t\t<div><img alt=\"\" src=\"img/elef.png\"></div>\n");
      out.write("\t\t<div><b>edicion general</b></div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<img alt=\"\" src=\"img/fb.png\">\n");
      out.write("\t\t\t<img alt=\"\" src=\"img/tw.png\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"rigth\">\n");
      out.write("\t\t\t<input id=\"search\" type=\"text\" placeholder=\"Buscar\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<nav>\n");
      out.write("        <ul>\n");
      out.write("            <li><a href=\"registrar-noticia.html\">enviar historia</a></li>\n");
      out.write("            <li><a href=\"\">portada</a></li>\n");
      out.write("            <li><a href=\"\">nuevas</a></li>\n");
      out.write("            <li><a href=\"\">populares</a></li>\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("    <article>\n");
      out.write("    \t<div class=\"titulo\">\n");
      out.write("    \t\t<div class=\"titulo-general\"><h2>Información del perfil:</h2></div>\n");
      out.write("    \t\t<div class=\"titulo-especifico\"><h2>nombreusuario</h2></div>\n");
      out.write("    \t</div>\n");
      out.write("    \t<div id=\"modif-perfil\">\n");
      out.write("    \t\t<input type=\"button\" value=\"Modificar Perfil\">\n");
      out.write("    \t</div><br/><br/>\n");
      out.write("    \t<fieldset>\n");
      out.write("    \t\t<legend>Información personal</legend>\n");
      out.write("    \t\t<div id=\"pic-user\">\n");
      out.write("    \t\t\t<img alt=\"avatar usuario\" src=\"img/pic-test.jpeg\">\n");
      out.write("    \t\t\t<input id=\"bt-cambiar\" type=\"button\" value=\"Cambiar\">\n");
      out.write("    \t\t</div>\n");
      out.write("    \t\t<table>\n");
      out.write("    \t\t\t<tbody>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>usuario:</th>\n");
      out.write("    \t\t\t\t\t<td>danielcb</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>desde:</th>\n");
      out.write("    \t\t\t\t\t<td>14/02/2016</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>karma:</th>\n");
      out.write("    \t\t\t\t\t<td>1000</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>noticias publicadas:</th>\n");
      out.write("    \t\t\t\t\t<td>1000</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>comentarios:</th>\n");
      out.write("    \t\t\t\t\t<td>1000</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t\t<tr>\n");
      out.write("    \t\t\t\t\t<th>numero de votos:</th>\n");
      out.write("    \t\t\t\t\t<td>1000</td>\n");
      out.write("    \t\t\t\t</tr>\n");
      out.write("    \t\t\t</tbody>\n");
      out.write("    \t\t</table>\n");
      out.write("\n");
      out.write("    \t</fieldset>\n");
      out.write("    \t<fieldset>\n");
      out.write("    \t\t<legend>Ultima dirección IP</legend>\n");
      out.write("    \t\t192.168.45.78\n");
      out.write("    \t</fieldset>\n");
      out.write("    </article>\n");
      out.write("    <footer>\n");
      out.write("\t    <div class=\"footer-sections\">\n");
      out.write("            <div class=\"section-separator\">\n");
      out.write("                <h4>Categorias</h4>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"\">Cultura</a></li>\n");
      out.write("                    <li><a href=\"\">Tecnologia</a></li>\n");
      out.write("                    <li><a href=\"\">Ocio</a></li>\n");
      out.write("                    <li><a href=\"\">Actualidad</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"section-separator\">\n");
      out.write("                <h4>Filtros</h4>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"registrar-noticia.html\">Enviar historia</a></li>\n");
      out.write("                    <li><a href=\"\">Portada</a></li>\n");
      out.write("                    <li><a href=\"\">Nuevas</a></li>\n");
      out.write("                    <li><a href=\"\">Populares</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div>\n");
      out.write("                <h4>Usuario</h4>\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"login.html\">Login</a></li>\n");
      out.write("                    <li><a href=\"ver-perfil.html\">Ver perfil</a></li>\n");
      out.write("                    <li><a href=\"modificar-perfil.html\">Modificar perfil</a></li>\n");
      out.write("                    <li><a href=\"modificar-borrar-noticia.html\">Ver mis noticias</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    \t<div class=\"footer-sections\">\n");
      out.write("    \t\t<img alt=\"\" src=\"img/logo-bottom.png\">\n");
      out.write("    \t\t<div id=\"copyrigth\">\n");
      out.write("    \t\t\t<a>legal </a>/\n");
      out.write("    \t\t\t<a>quienes somos </a>/\n");
      out.write("    \t\t\t<a>HTML5</a> |\n");
      out.write("    \t\t\tDaniel Correa Barrios, Universidad de Extremadura\n");
      out.write("    \t\t</div>\n");
      out.write("    \t</div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
